name: Pilipala Release

# action事件触发
on:
  push:
    # push tag时触发
    tags:
      - "v*.*.*"

# 可以有多个jobs
jobs:
  android:
    # 运行环境 ubuntu-latest window-latest mac-latest
    runs-on: ubuntu-latest

    # 每个jobs中可以有多个steps
    steps:
      - name: 代码迁出
        uses: actions/checkout@v3

      - name: 检查缓存
        uses: actions/cache@v2
        id: cache-flutter
        with:
          path: /root/flutter-sdk # Flutter SDK 的路径
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: 安装Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.4
          channel: any

      - name: 下载项目依赖
        run: flutter pub get

      - name: flutter build apk
        run: flutter build apk --release --split-per-abi

      - name: flutter build apk
        run: flutter build apk --release

      - name: 获取版本号
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >>$GITHUB_OUTPUT

      - name: 重命名应用
        run: |
          # DATE=${{ steps.date.outputs.date }}
          for file in build/app/outputs/flutter-apk/app-*.apk; do
            if [[ $file =~ app-(.?*)release.apk ]]; then
              new_file_name="build/app/outputs/flutter-apk/my_tv-${BASH_REMATCH[1]}${{ steps.version.outputs.version }}.apk"
              mv "$file" "$new_file_name"
            fi
          done

      - name: 上传
        uses: actions/upload-artifact@v3
        with:
          name: my_tv-Release
          path: |
            build/app/outputs/flutter-apk/my_tv-*.apk
